### ISSUE TITLE
Could've forked?

### ISSUE THREAD

**Issue by m4tt72** [Cveinnt/LiveTerm#15]
Was there something with the original project that prevented you from forking and creating a PR? It could have been a collaborative effort to make Terminal a better project for all, instead of taking it a different route by copying the repo, making minor esthetic modifications and pushing it as your own.

**Comment by Cveinnt** [comment]
Hey @m4tt72 , thanks for commenting - I originally made a fork of this, then decided to make several non-trivial code style/logical reorgs that eventually resulted in a separate repo. I've credited the original code both in README and license, and I hope that would clarify things. 
Please let me know what you think!

**Comment by m4tt72** [comment]
When I first stumbled upon this repo, I was confused why it exists knowing that there's no difference between this and my original repo, it does not bring any improvements to the code or the project itself. 

What stopped you from suggesting the changes you had in mind, and bring them to the original repo, instead of creating a new one? 

As I said previously, it could have been a collaborative effort to make the project better for everyone, not just yourself.

**Comment by Cveinnt** [comment]
Thanks for sharing your thoughts! 

> there's no difference between this and my original repo

Everything is open source, so feel free to compare the source code to see the difference :) 

> What stopped you from suggesting the changes you had in mind, and bring them to the original repo, instead of creating a new one?

As the changes are personal, I've decided not to make it into a clone of the original project. Though if you'd like, I can push some changes to your project that I've made in LiveTerm that wouldn't require major revamping of the original codebase. 

> it could have been a collaborative effort to make the project better for everyone, not just yourself.

I'm quite confused by this, are you implying that I open sourced LiveTerm for personal gain? From my perspective, there is little to nothing I can benefit from open sourcing a project other than the knowledge that it helped a lot of people. 

As the credits are appropriately attributed, I don't see why LiveTerm isn't an ongoing collaborative effort to make something better for everyone :)

**Comment by matmult** [comment]
@Cveinnt I think this is an excellent example of open source software working well, perhaps a little too well?
If my code is adopted for another project that ended up getting more stars and attention, I can't help feeling a tad bit jealous 😂

**Comment by m4tt72** [comment]
@sirjohnsonson I gotta admit, it is only normal to feel jealous. 

And to explain more my point of view @Cveinnt, from what I stand, I see someone publishing a repo that literally has most of the major parts copied, eg: shell, parsing commands, and UI, with some of the esthetics changed, publishing it everywhere as if they invented the whole thing.

What I would expect from someone wanting to tweak it to their own need, is to either suggest changed, that will benefit them, and see if it's gonna benefit the majority as well, for example: making it Mobile responsive, if that's what you wanted. And you would do the whole thing by forking the repo, to at least show that it is a fork, giving indirect credit, because that's what it is, and also benefit from new changes that are core to the project, instead of a new repo.

But hey, I'll quote this and resolve the issue here.

> this is an excellent example of open source software working well, perhaps a little too well?

PS: You might like what I did with the themes, and some restructuring using Context. Feel free to copy that as well ;)

**Comment by Cveinnt** [comment]
@m4tt72 thanks for sharing your perspective and I really appreciate the frank response! 

> publishing it everywhere as if they invented the whole thing.

I've never taken any credit for the work you did, and frankly, I am very sorry and embarrassed that I gave you that impression. Appropriating your work and call it as my own would defeat the entire point of open sourcing it - I'm sure you open sourced your project for the same reason: to help more people build cool websites, instead of merely using it for personal gain. 

I've only posted about LiveTerm on reddit (specifically r/unixporn and r/startpages), and it was only meant as a quick, configurable website builder for unix enthusiasts. Unfortunately, I could not control the spread of information, and many crossposted the project which made it blow up elsewhere. But I understand where you are coming from.  

Regardless, I tried my best to give direct credit/mentions in README and LICENSE, and made it clear that LiveTerm is built on top of open source efforts. I never intended to claim the project as solely my own. In retrospect, perhaps I should be more _considerate_ and should have done more - hope you can understand.

I'm glad you liked my idea of having a themes manager! Looks like you've made it better :D Perhaps we can work on integrating `fetch` along with other LiveTerm utilities to your project as well!
